## This notebook consist of Numpy Library and it's different use

### Numpy is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more

In [1]:
# importing libarires

import numpy as np
import warnings

In [2]:
np.version.version

'1.18.1'

## Trigonometric function in Numpy

In [3]:
in_arr = [0,np.pi/2,np.pi/3,np.pi]
in_arr

[0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]

In [4]:
sin_arr = np.sin(in_arr)
sin_arr

array([0.00000000e+00, 1.00000000e+00, 8.66025404e-01, 1.22464680e-16])

In [5]:
cos_arr = np.cos(in_arr)
cos_arr

array([ 1.000000e+00,  6.123234e-17,  5.000000e-01, -1.000000e+00])

In [6]:
tan_arr = np.tan(in_arr)
tan_arr

array([ 0.00000000e+00,  1.63312394e+16,  1.73205081e+00, -1.22464680e-16])

In [7]:
arr = np.arange(10.)*50
arr

array([  0.,  50., 100., 150., 200., 250., 300., 350., 400., 450.])

In [8]:
# Convert degree to radians
rad = np.radians(arr)
rad

array([0.        , 0.87266463, 1.74532925, 2.61799388, 3.4906585 ,
       4.36332313, 5.23598776, 6.10865238, 6.98131701, 7.85398163])

In [9]:
# Similar method to convert degree to radians
deg2rad = np.deg2rad(arr)
deg2rad

array([0.        , 0.87266463, 1.74532925, 2.61799388, 3.4906585 ,
       4.36332313, 5.23598776, 6.10865238, 6.98131701, 7.85398163])

In [10]:
deg = np.degrees(arr)
deg

array([    0.        ,  2864.78897565,  5729.57795131,  8594.36692696,
       11459.15590262, 14323.94487827, 17188.73385392, 20053.52282958,
       22918.31180523, 25783.10078089])

## Random Number in Numpy

In [11]:
np.random.seed(1)
np.random.randint(1,15, size = (5,5))

array([[ 6, 12, 13,  9, 10],
       [12,  6,  1,  1,  2],
       [13,  8, 14, 13,  7],
       [10,  3,  5,  6,  3],
       [ 5, 12, 13, 11, 13]])

In [12]:
np.random.seed(5)
np.random.random(size=(5,5))

array([[0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119],
       [0.61174386, 0.76590786, 0.51841799, 0.2968005 , 0.18772123],
       [0.08074127, 0.7384403 , 0.44130922, 0.15830987, 0.87993703],
       [0.27408646, 0.41423502, 0.29607993, 0.62878791, 0.57983781],
       [0.5999292 , 0.26581912, 0.28468588, 0.25358821, 0.32756395]])

## Hyperbolic function in Numpy

In [13]:
#Finding angle of sinh
x= np.arcsinh(1.0)
x

0.881373587019543

In [14]:
#Finding the angle of tanh
y=np.array([0.1,0.2,0.5])
x=np.arctanh(y)
x

array([0.10033535, 0.20273255, 0.54930614])

In [15]:
#Finding cosh values
arr = np.array([np.pi/2,np.pi/3,np.pi/4])
x=np.cosh(arr)
x

array([2.50917848, 1.60028686, 1.32460909])

## Fucntion of Rounding

In [16]:
#truncate function
t_arr = np.trunc([-3.895, 4.456])
t_arr

array([-3.,  4.])

In [17]:
# fix function
f_arr = np.fix([-4.567,1.890])
f_arr

array([-4.,  1.])

In [18]:
#The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.
r_arr = np.around([7.568,8.1234,5.6789])
r_arr

array([8., 8., 6.])

In [19]:
#The floor() function rounds off decimal to nearest lower integer.
fl_arr = np.floor([7.567,6.123,7.890])
fl_arr

array([7., 6., 7.])

In [20]:
#The ceil() function rounds off decimal to nearest upper integer.
c_arr = np.ceil([5.456,7.890])
c_arr

array([6., 8.])

## Exponents & Logarthims Function

In [21]:
np.log(np.e**4) 
np.log2(2**4)   
np.log10(10**4) 

4.0

In [22]:
import math
number = 74088  
base = 42
exponent = math.log(number, base)
exponent

3.0

## Arithmetic Function

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
a = np.arange(9, dtype = np.float_).reshape(3,3) 
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [26]:
b = np.array([10,10,10])
b

array([10, 10, 10])

In [27]:
np.reciprocal(b)

array([0, 0, 0], dtype=int32)

In [28]:
c = np.array([25, 1.33, 1, 35])
np.reciprocal(c)

array([0.04      , 0.7518797 , 1.        , 0.02857143])

In [29]:
np.add(a,b)

array([[10., 11., 12.],
       [13., 14., 15.],
       [16., 17., 18.]])

In [30]:
np.subtract(a,b)

array([[-10.,  -9.,  -8.],
       [ -7.,  -6.,  -5.],
       [ -4.,  -3.,  -2.]])

In [31]:
np.divide(a,b)

array([[0. , 0.1, 0.2],
       [0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8]])

In [32]:
np.power(a,2)

array([[ 0.,  1.,  4.],
       [ 9., 16., 25.],
       [36., 49., 64.]])

In [33]:
np.power(a,b)

array([[0.00000000e+00, 1.00000000e+00, 1.02400000e+03],
       [5.90490000e+04, 1.04857600e+06, 9.76562500e+06],
       [6.04661760e+07, 2.82475249e+08, 1.07374182e+09]])

In [34]:
np.divmod(a,b)

(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]]))

In [35]:
np.mod(a,b)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

## Special Function 

In [36]:
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [37]:
#cuberoot
np.cbrt(a)

array([[0.        , 1.        , 1.25992105],
       [1.44224957, 1.58740105, 1.70997595],
       [1.81712059, 1.91293118, 2.        ]])

In [38]:
np.clip(a, 1, 4)

array([[1., 1., 2.],
       [3., 4., 4.],
       [4., 4., 4.]])

In [39]:
np.sqrt(b)

array([3.16227766, 3.16227766, 3.16227766])

In [40]:
np.square([3,8,10])

array([  9,  64, 100], dtype=int32)

In [41]:
np.absolute([-67,90,-87])

array([67, 90, 87])

In [42]:
np.maximum(np.eye(4), [0.5, 2,4,8]) 

array([[1. , 2. , 4. , 8. ],
       [0.5, 2. , 4. , 8. ],
       [0.5, 2. , 4. , 8. ],
       [0.5, 2. , 4. , 8. ]])

In [43]:
np.maximum([2, 3, 4], [1, 5, 2],)

array([2, 5, 4])

In [44]:
np.minimum([2, 3, 4], [1, 5, 2])

array([1, 3, 2])

In [45]:
#Element-wise minimum of two arrays, ignores NaNs.
np.fmin([2, 3, 4], [1, 5, 2])

array([1, 3, 2])

In [46]:
np.heaviside([-1.5, 0, 2.0], 0.5)

array([0. , 0.5, 1. ])

In [47]:
np.heaviside([-1.5, 0, 2.0], 1)

array([0., 1., 1.])